# Generated by Django 3.0 on 2019-12-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191209_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='sides',
            field=models.CharField(choices=[('chips', 'Chips'), ('soup', 'Soup of the day'), ('vegies', 'Assorted Veggies'), ('bread', 'Bread')], default='chips', max_length=20),
        ),
    ]
