# Generated by Django 3.0 on 2019-12-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_meal_sides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='sides',
            field=models.CharField(choices=[('chips', 'Chips'), ('soup', 'Soup of the day'), ('veggies', 'Assorted Veggies'), ('bread', 'Bread')], default='chips', max_length=20),
        ),
    ]
