# Generated by Django 3.0 on 2020-04-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191229_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='rating',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default='NOT_PROVIDED', max_length=5),
        ),
        migrations.AlterField(
            model_name='meal',
            name='details',
            field=models.CharField(max_length=75),
        ),
    ]
